<?php
/**
 * Created by PhpStorm.
 * user: thinkgamer
 * Date: 18-4-15
 * Time: 上午10:47
 */
namespace app\admin\model;
use think\Controller;
use think\Cookie;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 获取已登录用户名，查询数据库角色
        $username = Cookie::get('username');  // 获取cookie 用户名
        $user = db('employee')->where('loginname', $username)->find();

        // 获取有多少条站内信
        if($user['role'] == 1){ // 超级管理员
            $map['is_see_role1']=0;
            $map['is_operation']=0;
            $mess_num1=db('news')->where($map)->count();
            $map1['is_action']=0;
            $map1['is_operation']=1;
            $mess_num2=db('news')->where($map1)->count();
            $mess_num =$mess_num1+$mess_num2;
        }elseif($user['role'] == 2){ // 网点负责人
            $map['point']=array('eq',$user['point']);
            $map['is_see_role2']=array('eq',0);
            $map['has_permission_point']=array('eq',1);
            $mess_num1=db('news')->where($map)->count();
            $map1['point']=array('eq',$user['point']);
            $map1['has_permission_point']=array('eq',1);
            $map1['is_action']=0;
            $map1['is_operation']=1;
            $mess_num2=db('news')->where($map1)->count();
            $mess_num=$mess_num1+$mess_num2;
        }elseif ($user['role'] == 3){
            $map['point']=array('eq',$user['point']);
            $map['is_see_role3']=array('eq',0);
            $map['has_permission_people']=array('eq',1);
            $map['has_permission_point']=array('eq',0);
            $mess_num=db('news')->where($map)->count();
        }else{
            $mess_num=0;
        }

        $this->role = $user['role'];
        $this->point = $user['point'];
        $this->uname = $username;
        $this->messnum = $mess_num;
    }

    public function write($main1="",$action="",$main2="",$point="",$has_permission_point=0,$has_permission_people=0)
    {
        $data=[
            "main1"=>$main1,"action=$action","main2"=>$main2,"point"=>$point,
            "has_permission_point"=>$has_permission_point,"has_permission_people"=>$has_permission_people
        ];
        db('nrews')->insert($data);
    }
}